; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino


; 1. High-speed monitoring (Matches the Agent's 921600 baud)
monitor_speed = 921600

; 2. The critical micro-ROS library dependency
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio

; 3. Transport configuration (Tells micro-ROS to use the Serial/USB cable)
board_microros_transport = serial

; 4. Optional: Optimization (Forces the compiler to use speed optimizations)
build_flags =
    -O3
    -D SKIP_TESTS=ON
    -D MICROROS_CONFIG_FILE=extra/microros_config.meta